version: '3'

services:
  web:
    container_name:                 "wagtail"
    environment:
      # Postgres
      DBHOST:                       "0.0.0.0"
      DBNAME:                       "django"
      DBUSER:                       "docker"
      DBPASSWORD:                   "docker"
      DBPORT:                       "3001"
      SEARCHAPIHOST:                "${SEARCHAPIHOST}"
      WIDGETAPIHOST:                "${WIDGETAPIHOST}"
      WIDGETAPIKEY:                 "${WIDGETAPIKEY}"
      DATASETAPIHOST:               "${DATASETAPIHOST}"
      DATASETAPIKEY:                "${DATASETAPIKEY}"
      AZURECOSMOSDBURI:             ""
      AZURECOSMOSDBKEY:             ""
      MONGODB_HOST:                 "0.0.0.0"
      MONGODB_USERNAME:             "mongodb"
      MONGODB_PASSWORD:             "mongodb"
      TEST_COURSES:                 ""
      STORAGE_ACCOUNT_NAME:         "${STORAGE_ACCOUNT_NAME}"
      STORAGEKEY:                   "${STORAGEKEY}"
      AZURE_ACCOUNT_NAME:           "${AZURE_ACCOUNT_NAME}"
      AZURE_ACCOUNT_KEY:            "${AZURE_ACCOUNT_KEY}"
      AZURE_CONTAINER:              "${AZURE_CONTAINER}"
      SENDGRID_API_KEY:             "${SENDGRID_API_KEY}"
      SECRET_KEY:                   "${SECRET_KEY}"
      SENDGRID_FROM_EMAIL:          "${SENDGRID_FROM_EMAIL}"
      FEEDBACK_API_HOST:            "${FEEDBACK_API_HOST}"
      JSONFILES_STORAGE_CONTAINER:  "${JSONFILES_STORAGE_CONTAINER}"
      ROOT_DOMAIN:                  "${ROOT_DOMAIN}"
      READ_ONLY:                    "${READ_ONLY}"
      LOCAL:                        "${LOCAL}"
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
