version: '3'

services:
  web:
    environment:
      DBNAME: "${DBNAME}"
      DBHOST: "${DBHOST}"
      DBUSER: "${DBUSER}"
      DBPORT: "${DBPORT}"
      DBPASSWORD: "${DBPASSWORD}"
      SEARCHAPIHOST: "${SEARCHAPIHOST}"
      DATASETAPIHOST: "${DATASETAPIHOST}"
      WIDGETAPIKEY: "${WIDGETAPIKEY}"
      WIDGETAPIHOST: "${WIDGETAPIHOST}"
      DATASETAPIKEY: "${DATASETAPIKEY}"
      FEEDBACK_API_HOST: "${FEEDBACK_API_HOST}"
      JSONFILES_STORAGE_CONTAINER: ${JSONFILES_STORAGE_CONTAINER}
      AZURE_ACCOUNT_NAME:  "${AZURE_ACCOUNT_NAME}"
      AZURE_ACCOUNT_KEY:  "${AZURE_ACCOUNT_KEY}"
      AZURE_CONTAINER:  "${AZURE_CONTAINER}"
      READ_ONLY:  "${READ_ONLY}"
      ROOT_DOMAIN: "${ROOT_DOMAIN}"
      LOCAL: "${LOCAL}"
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    command: bash -c "sh ./deploy_files/docker-entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
